# For Local - Added host to check

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mern-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /  # ensures paths are forwarded correctly
# spec:
#   ingressClassName: nginx    # must match your ingress controller
#   rules:
#   - host: mern.local // For local
#     http:
#       paths:
#       # Frontend (React) serves everything except /api
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend-service
#             port:
#               number: 80
#       # Backend (Express) serves /api requests
#       - path: /api
#         pathType: Prefix
#         backend:
#           service:
#             name: backend-service
#             port:
#               number: 5000

# For AWS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # ensures paths are forwarded correctly
spec:
  ingressClassName: nginx    # must match your ingress controller
  rules:
  - http:
      paths:
      # Frontend (React) serves everything except /api
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
